# src/garage/services/storage/base.py
"""
Abstract base class for storage backends.

WHY AN ABSTRACT CLASS:
- Defines a contract: "all storage backends must have these methods"
- Python will raise an error if you forget to implement a method
- Makes it clear what the storage interface looks like
- Enables type hints: functions can accept `StorageBackend` type

WHAT EACH METHOD DOES:
- save_image(): Save an uploaded file (from form), return URL
- save_qr(): Save a generated QR code image, return URL
- delete(): Remove a file from storage
- get_url(): Convert stored path to displayable URL
- exists(): Check if a file exists

All concrete implementations (LocalStorageBackend, S3StorageBackend)
must implement every method marked with @abstractmethod.
"""
from abc import ABC, abstractmethod
import logging
from typing import BinaryIO

from PIL import Image


class StorageBackend(ABC):
    """
    Abstract interface for file storage operations.
    
    This class cannot be instantiated directly.
    Use LocalStorageBackend or S3StorageBackend instead.
    """
    
    def __init__(self):
        """
        Initialize the storage backend with a logger.
        
        Each subclass gets a logger named after its class,
        making it easy to see which backend logged a message.
        """
        self.logger = logging.getLogger(self.__class__.__name__)
    
    @abstractmethod
    def save_image(
        self,
        file: BinaryIO,
        box_id: int,
        image_type: str = 'box'
    ) -> str | None:
        """
        Save an uploaded image file.
        
        Args:
            file: File-like object (e.g., from request.files['image'])
            box_id: ID of the associated box (used in filename)
            image_type: 'box' for box photos, 'qr' for QR codes
        
        Returns:
            Path or URL to saved file, or None on failure
        
        Note: Implementations must handle:
        - Creating directories if needed
        - Generating unique filenames
        - Logging success/failure
        """
        pass
    
    @abstractmethod
    def save_qr(self, image: Image.Image, box_id: int) -> str | None:
        """
        Save a PIL Image (QR code).
        
        This is separate from save_image because:
        - QR codes are generated by the app, not uploaded
        - They're PIL Image objects, not file uploads
        - They have consistent naming (always PNG)
        
        Args:
            image: PIL Image object (from qrcode library)
            box_id: ID of the associated box
        
        Returns:
            Path or URL to saved file, or None on failure
        """
        pass
    
    @abstractmethod
    def delete(self, file_path: str) -> bool:
        """
        Delete a file from storage.
        
        Args:
            file_path: Path or URL to delete
                      (whatever was returned by save_image/save_qr)
        
        Returns:
            True if deleted successfully
            False if file not found or error occurred
        
        Note: Should NOT raise exceptions for missing files.
        """
        pass
    
    @abstractmethod
    def get_url(self, file_path: str) -> str | None:
        """
        Get displayable URL for a file.
        
        This handles the difference between:
        - Local: "static/images/box_1.png" -> "/static/images/box_1.png"
        - S3: Return the full HTTPS URL
        
        Args:
            file_path: Stored path or URL (from database)
        
        Returns:
            URL suitable for use in templates
            None if file_path is None/empty
        """
        pass
    
    @abstractmethod
    def exists(self, file_path: str) -> bool:
        """
        Check if a file exists in storage.
        
        Args:
            file_path: Path or URL to check
        
        Returns:
            True if file exists, False otherwise
        """
        pass